#!/usr/bin/env bash
# configures an Ubuntu server with localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8.
facebook.com resolves to 8.8.8.8.
cat <<EOF > /etc/hosts
127.0.0.2 localhost
8.8.8.8 facebook.com
EOF
